FROM debian

# Install required iproute2 package
RUN apt install iproute2

# Install resolve docker host IP script
COPY --from=tkotosz/resolve-docker-host-ip /usr/bin/resolve-docker-host-ip /usr/local/bin/resolve-docker-host-ip

# Wrap the entry point (sleep infinity) so that the host IP is resolved when the container started
ENTRYPOINT ["/usr/local/bin/resolve-docker-host-ip","sleep","infinity"]
